//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Survey
    {
        public User_Survey()
        {
            this.Survey_Q_User = new HashSet<Survey_Q_User>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> FK_ServerId { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual ICollection<Survey_Q_User> Survey_Q_User { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
