// <auto-generated />
namespace Survey.Ef.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddSurveyQAnswerUserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSurveyQAnswerUserName));
        
        string IMigrationMetadata.Id
        {
            get { return "202011111101591_AddSurveyQAnswerUserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
